### ISSUE TITLE
broken throwing and gui spear models

### ISSUE THREAD

**Issue by k1r0s** [theishiopian/Parrying#10]

**Comment by k1r0s** [comment]
not sure how to fix this:

src\main\java\com\theishiopian\parrying\Mixin\ItemRendererMixin.java

i've been messing around with the model path by removing "_gui" and getting some results but not completly done. Like the spear rendering but pointing backwards in throwing animation, and the gui icon being the big one 32x32 instead of the small 16x16 one.

**Comment by theishiopian** [comment]
I'm not sure what the problem is. Are you trying to modify the code?

**Comment by k1r0s** [comment]
latest build has rendering errors

**Comment by k1r0s** [comment]
![2021-11-15_09 26 55](https://user-images.githubusercontent.com/6052309/141747679-a8e780a9-9b35-451e-b334-077dd054ca9f.png)

gui models are not shown and throwing models do not work either

**Comment by k1r0s** [comment]
so I've asked over the internet and I got this. Im trying to make it work
https://github.com/MinecraftForge/MinecraftForge/blob/fed7beab89031a4ca3786dcda4d4c21f702f6dfb/src/generated_test/resources/assets/new_model_loader_test/models/item/separate_perspective.json

**Comment by k1r0s** [comment]
I've just compiled my own version without the mixin, basically I applied the spear_big texture in all cases. To me this is enough. I want to play xd

**Comment by theishiopian** [comment]
This error is not present in build, I tested thouroughly. what mods do you have? can you send logs?

**Comment by k1r0s** [comment]
I've downloaded the code from here and run it locally. 

however its true that nobody is reporting it, quinda weird. ..

let me check when I get home

**Comment by k1r0s** [comment]
closing this as im not able to reproduce it on windows 10. Will open again if I find more information about. thx

**Comment by theishiopian** [comment]
If you are able to reproduce it and identify the conditions dont hesitate to reopen this. that whole system is held togetehr with the code equivalent of duct tape, so I wanna keep a close eye on it.

**Comment by k1r0s** [comment]
Yes, I've been looking at it but no way to reproduce it outside of windows 7.

However I guess my graphic card drivers are to blame since the card is quite old (gigabyte GT 630). 

A side of that Its true that the piece of code is quite pasta but I don't have much experience in Java, nor forge modding, to suggest alternatives. 

Btw I've been asking to forge devs and they told me to take a look that what the minecraft devs did in order to render the trident it self. They used a handler called itemstackrenderer or something like that which is more advanced that a bakedModel.

**Comment by theishiopian** [comment]
I have a policy to not directly ask the forge devs for anything anymore, I find them insufferably abrasive. However, I will keep that in mind. The current solution was always meant to be temporary anyways.

**Comment by theishiopian** [comment]
I appreciate you trying to help!

**Comment by theishiopian** [comment]
The code you sent earlier looks interesting, ill see if I can leverage that. I had missed it before.

**Comment by theishiopian** [comment]
Just pushed a rework using the thing you linked, see if that works any better

**Comment by k1r0s** [comment]
it works, just checked <3 amazing

**Comment by k1r0s** [comment]
will take a look over what you did in the code

**Comment by k1r0s** [comment]
:laughing: 
https://github.com/theishiopian/Parrying/commit/7d9d21f603bb7d071124e69875081bd8ae789c1e

**Comment by theishiopian** [comment]
Once again lack of documentation of useful and well amde features messes me up lmao
