### ISSUE TITLE
[ Issue ] java.lang.IllegalStateException

### ISSUE THREAD

**Issue by zndrmn** [theishiopian/Parrying#11]
### **[ Issue ] java.lang.IllegalStateException**
_java.lang.IllegalStateException: Tag parrying:two_handed_weapons used before it was bound
This happened after removing and adding a new texturepack, the texturepack does edit some of the textures inside Parrying_
- - -
MC **: 1.16.5**
Forge **: 36.2.8**
OptiFine **: HD_U_G8**
Shader Name **: ComplementaryShaders_v4.3_dev3**
Mod Name **: parrying-2.2.0**
- - -
Crash Report **: https://gist.github.com/zndrmn/e20a6b4f0b048817c0b4cc5335aabd2c#file-crash-2021-11-14_18-25-18-client-txt**
Latest.log **: https://gist.github.com/zndrmn/1f0a149eacae66273005e1fb5f3e7c39#file-latest-log**

**Comment by theishiopian** [comment]
Thank you for the logs, this probably won't be hard to fix

**Comment by theishiopian** [comment]
I am unable to reproduce this issue, can you test this without optifine, and with a different texture pack? If it only occurs with your pack can you send me a link to it?

**Comment by zndrmn** [comment]
It seems to have fixed itself with the latest version of the mod.

**Comment by theishiopian** [comment]
Bizzare. let me know if it happens again
