### ISSUE TITLE
Spears Missing Texture in Inventory. 

### ISSUE THREAD

**Issue by PhweeDev** [theishiopian/Parrying#14]
The wooden, stone, iron, golden, diamond, and netherite spears are shown with the pink/black missing texture.

**Comment by theishiopian** [comment]
please send logs, a mod list, and any other information about your setup that might contribute

**Comment by k1r0s** [comment]
@Phweeeee which OS are you using? I had a similar issue #10

**Comment by k1r0s** [comment]
check the latest version pls
