### ISSUE TITLE
[ Suggestion ] Parrying reset or reduce attack cooldown

### ISSUE THREAD

**Issue by MrHazMat** [theishiopian/Parrying#15]
I'm not sure if it's feasible but it would be interesting if player successfully parrying can sneak another attack quickly instead of waiting out the cooldown

**Comment by theishiopian** [comment]
That is a very strong ability, having it by default would be too strong. However, it might make a more interesting mechanic for the riposte enchantment, which I've never been happy with. I'll think about it.

**Comment by MrHazMat** [comment]
I'm not a fan of mechanics locked behind by enchantment. I think it's balanced out by the fact there's no indication for mobs' attack, which mean player need precise timing, and would incentivise parrying.

On another note, I noticed that player has a huge window of parrying, I noticed this after trying to parry Ferrous Wroughnot from Mowzie's Mobs mod. Is this an intended mechanic?

**Comment by theishiopian** [comment]
Yes. I tried making it time limited, but in playtests it just wasnt as fun, and made parrying mobs practically impossible. It does seem like a good idea in theory but in practice it just makes the mechanic frustrating to use. The best counter to parrying is to sidestep, speed and jump boost will help with this
