### ISSUE TITLE
Parrying weapons cannot receive other enchantments

### ISSUE THREAD

**Issue by k1r0s** [theishiopian/Parrying#17]
I guess this is not intended

**Comment by theishiopian** [comment]
Minecraft is very picky about what can and cannot have specific enchantments. I can of course work around this, but it has to be done specifically for each enchantment (for example smite on bludgeoning). Ideas on what items should be able to receive what enchants from vanilla are appreciated.

**Comment by k1r0s** [comment]
https://forums.minecraftforge.net/topic/96851-1164-custom-item-enchantability/

**Comment by k1r0s** [comment]
https://github.com/BobMowzie/MowziesMobs/blob/master/src/main/java/com/bobmowzie/mowziesmobs/server/item/ItemNagaFangDagger.java#L28

**Comment by k1r0s** [comment]
![2021-11-26_01 20 52](https://user-images.githubusercontent.com/6052309/143509979-cc2e5e35-867d-409e-a2c9-3794d461b54c.png)

**Comment by theishiopian** [comment]
Fixed in 1.18, thanks @k1r0s for the help.
