### ISSUE TITLE
Game sometimes crashes when typing in a name for a new world

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [theishiopian/Parrying#2]
Forge Version: 36.1.32
Parrying Version: 1.9.1
Crash Report: https://gist.github.com/NJL5390/42dd4e6608059c77d5f78fbafd64a9fa

I want to start off by saying I love the concept for this mod and have really enjoyed using it lately! There's not many like it on modern versions of Minecraft!

Now, To the problem at hand, I've been getting this crash lately after updating to the latest version of this mod. It only seems to  happen when I'm in the main menu and typing the name of a new world for example. The crash report seems to mention your mod so maybe you know what's going on here?

Thanks for the fantastic mod and keep up the great work!

(EDIT: Forget about the startup crash, that's an issue with a different mod unrelated to yours.)

**Comment by theishiopian** [comment]
dammit, this is dumb. i know what's causing this, ill fix it next time i work on the mod

**Comment by theishiopian** [comment]
Thanks for letting me know, this whole getting key input thing is rather finicky

**Comment by theishiopian** [comment]
Ok, this shouldn't be an issue anymore. I unfortunately cant reproduce it on my end, but based on the log i think this should fix it. Once the update comes out let me know if this happens again and I will reopen the issue.

**Comment by The-Bernician-Lamb** [comment]
This seems to have fixed the issue. Thanks a lot!
