### ISSUE TITLE
[ CLIENT : Issue ] Java.lang.IllegalStateException

### ISSUE THREAD

**Issue by zndrmn** [theishiopian/Parrying#20]
### **[ CLIENT : Issue ] Java.lang.IllegalStateException**
_Description: Rendering overlay, java.lang.IllegalStateException: Tag parrying:two_handed_weapons used before it was bound . . ._

This issue is similar to issues #11 ( Closed ) & #19 ( Open )
- - -
MC **: 1.16.5**
Forge **: 36.2.8**
OptiFine **: HD_U_G8**
Shader Name **: ComplementaryShaders_v4.3.2**
Mod Name **: parrying-2.2.2**
- - -
Crashy [ _BETA_ ] **: https://crashy.net/GutavpkxuJx6053p46mD**

Crash Report **: https://gist.github.com/zndrmn/dc87ce1fe677779c4f9e00d30aa6201c#file-crash-2021-12-14_06-10-32-client-txt**
Latest.log **: https://gist.github.com/zndrmn/21c117f08455b9094f49a17b048b6e1d#file-latest-log**

**Comment by theishiopian** [comment]
Will keep track of this on #21
