### ISSUE TITLE
Game crashing when minecraft trying restart to changes something.

### ISSUE THREAD

**Issue by qqq0201** [theishiopian/Parrying#22]
My game is crashing, when i trying to change resource pack or even a game language. The most interesting thing is even i dont change anything and click apply, minecraft trying to restart to apply changes, which I did not do (minecraft do it allways when u change resource pack or something). And when it happens my game is crashing, it doesn't matter if I changed something or not my game is isnantly crashing. I tested it on almost clean minecraft (OptiFine-1.16.5_HD_U_G8_pre2 and Forge 36.2.22) thats all. (Sorry for my english)

**Comment by theishiopian** [comment]
Please post a full crash log and game logs, if you have them

**Comment by theishiopian** [comment]
Also, please repost this to #21
