### ISSUE TITLE
parry this weapons accept sweeping edge even when it doesn't make sense

### ISSUE THREAD

**Issue by esotericist** [theishiopian/Parrying#23]
version 2.3, on forge 1.18.1-39.0.10

noticed this while looking at enchantment options for a spear, realized it also applied to the rest of the parry this weapons.

is it possible to limit sweeping edge applicability to just parry this weapons that it works on (just the flail, i think?)

**Comment by k1r0s** [comment]
By default all weapon enchantments are applied to parrythis weapons. It might be a bug since sweeping edge can only be applied to swords. This is a no op and should be removed.

**Comment by theishiopian** [comment]
Minecraft, by default, has only one kind of "weapon", as such anything considered a weapon can take weapon enchants. I've been slowly working on this, but it's like playing whack-a-mole

**Comment by theishiopian** [comment]
Should be fixed with latest commit
