### ISSUE TITLE
spears damage mounted entities

### ISSUE THREAD

**Issue by k1r0s** [theishiopian/Parrying#25]
I dunno, like spears do not extend from SwordItem so that makes difficult to workaround for other mods like quark to avoid damaging your own pets. 

In this case is even more anoying since you attack with the spear while mounting a horse and your attacks almost always damage them.

Any solution to avoid it?

**Comment by theishiopian** [comment]
I'll add this to the list, shouldnt be too difficult.

**Comment by k1r0s** [comment]
thx! do you have any clues for me to implement, im playing on 1.16

**Comment by theishiopian** [comment]
What do you mean?

**Comment by theishiopian** [comment]
I just tested, spears do not damage mounted entities.

**Comment by theishiopian** [comment]
https://user-images.githubusercontent.com/8585975/161403516-53be0c85-caf3-4d50-8b1b-7e9b2754d935.mp4

proof

**Comment by k1r0s** [comment]
yes, in 1.16 it does. Will check what I can do

**Comment by theishiopian** [comment]
1.16 is no longer supported
