### ISSUE TITLE
Crash network game

### ISSUE THREAD

**Issue by misha90122** [theishiopian/Parrying#26]
The game crashes when switching to a network game, when I click the network game, the game crashes
crash reports:
[crash-2022-04-02_14.17.26-client.txt](https://www.upload.ee/download/14016386/eea8f1f217541acecd9d/crash-2022-04-02_14.17.26-client.txt)
[crash-2022-04-02_14.17.34-client.txt](https://www.upload.ee/download/14016383/cb53740d3a9e1acecd7f/crash-2022-04-02_14.17.34-client.txt)

**Comment by theishiopian** [comment]
Please post your logs to pastebin. Also, what is a "network game"?

**Comment by misha90122** [comment]
![image](https://user-images.githubusercontent.com/102859568/161427840-2b5d4bff-7362-47f0-9a12-7f8f74647c1f.png)

I also noticed that on version 2.3 the game with the mod (cherishedworlds) crashes when adding a world \ server to favorites, but I have crashes and by simply pressing the buttons in the menu, even without the cherishedworlds mod, I also noticed that on 2.4, everything works more stable, and does not crash, but crashes when clicking on a network game and sometimes when adding a world to favorites (mod cherishedworlds)

**Comment by misha90122** [comment]
> Пожалуйста, выкладывайте логи на pastebin. Кроме того, что такое «сетевая игра»?

Where are the pastebin logs located?

**Comment by misha90122** [comment]
> Please post your logs to pastebin. Also, what is a "network game"?

Where are the pastebin logs located?

**Comment by misha90122** [comment]
Maybe it will be useful, here is the assembly of mods in which I added this mod https://drive.google.com/file/d/16OooURCh2NwMbtuxnRG_0C9Ejc7QI9om/view?usp=sharing

**Comment by theishiopian** [comment]
Pastebin is a website for posting large amounts of text to. I prefer it for reading logs, makes things easier. The mod list is EXTREMELY helpful, as it allows me to locate a possible conflict. This mod has been extensively multiplayer tested with no issues, so I suspect that one of your mods has a mixin that targets a similar spot to one of mine.

**Comment by misha90122** [comment]
I decided to try to update to version 2.4.2, but the game still crashes when trying to enter multiplayer, the launch was without a mod (cherishedworlds), I decided to make a report again, I think it will be useful, this report can be more detailed and useful as I used mod (not-enough-crashes this time)
https://bytebin.lucko.me/Sc5WyzjMCz
https://crashy.net/W9RJf7mHtIOJc1KfWTzE

**Comment by theishiopian** [comment]
does this still happen on 1.18.2?

**Comment by theishiopian** [comment]
Closing for now
