### ISSUE TITLE
Game crashes with Unidentified Enchantments when mousing over the quiver

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [theishiopian/Parrying#30]
Minecraft version: 1.18.2
Parry this! version: 2.5
Forge Version: 40.1.54
Unidentified Enchantments Version: 1.0.9
Crash Report: https://gist.github.com/NJL5390/0aacf80a53aff0a354c3525ed7795968

Hi,

After testing the latest alpha for Parry This! in my modpack I noticed that it was crashing whenever I tried to hover over the new quiver item. The crash report indicates that is in relation to unidentified enchantments (https://www.curseforge.com/minecraft/mc-mods/unidentified-enchantments). 

The testing that I have done confirms this suspicion, if I remove Unidentified enchantments then the crash stops happening. I will report this to their github as well as there may be some compatibility needed on their end due to how their mods works but I'm not entirely sure. 

I will put the link below when I have reported this to them.

Thanks for the great mod! It makes combat so much more interesting and has easily become my favourite combat based mod!

UPDATE: Here is the issue on their github: https://github.com/ferriarnus/Unidentified-Enchantments/issues/16

**Comment by theishiopian** [comment]
It appears my capability implementation may be the issue, I'm guessing all the other crashes are related to this. I'm a little busy atm so I will take a look as soon as i can.
