### ISSUE TITLE
Crash on dedicated server, regression issue #21

### ISSUE THREAD

**Issue by NighthowlerStudios** [theishiopian/Parrying#36]
The recent fix that was given to #21 caused a regression in registry systems, where IRenderAsItem cannot be referenced as it is a no class defined error whatsoever on a dedicated server.  this is because that class does not exist on servers.  maybe the entire check could also get a DEDICATED_SERVER only-in tag?

https://pastebin.com/zcQW1BrG

**Comment by NighthowlerStudios** [comment]
I believe this to be the case, because dedicated servers can safely stay downgraded to 2.2.2 whilst the client remains at 2.2.2a.  the client will still connect as expected and function correctly.

**Comment by theishiopian** [comment]
Unfortunately 2.2.2a is not officially supported, it was donated by AHilyard. If they want to fix it, thats up to them.
