### ISSUE TITLE
Suggestion: Disabling Items should also remove them from Loot Tables

### ISSUE THREAD

**Issue by ShinryuAspect** [theishiopian/Parrying#40]
It may be just a bug with the self made modpack that I've built, but I disabled both the Quiver and the Scabbard and I manage to find one of them (to be precise, a Scabbard) inside a chest. Don't know if it may also happen withthe Quiver or the Weapons (I've also disabled those as I'm okay with Vanilla weapons and the mechanics of the mod it what I was looking for), as I've not spent yet a lot of time inside the world openning loot chests.
Also, I'm not aware of how easy/difficulty could be to unregister such things from loot tables. If it's not a hard tweak, maybe an extra bool in the config to have those features appart from one another (one to disable the recipe and another to disable from loot tables).

**Comment by theishiopian** [comment]
Ill look into this.
