### ISSUE TITLE
[Suggestion] Make arrows fired by Scoped Crossbow be affected by gravity after a long time, or when hitting water

### ISSUE THREAD

**Issue by deadlymango** [theishiopian/Parrying#41]
Forge version: 40.1.51
Mod version: parrying-1.18.2-2.5.2.jar

While messing around with the scoped crossbow, I found that if you shoot the arrow into a body of water, it will slow down as a normal arrow does, but since it has no gravity, it will stop and remain suspended in the water indefinitely. I think it would make more sense for the arrow to either be affected by gravity after it has been in flight for a sufficient amount of time, or for the arrow to become affected by gravity upon touching water.

Example video of the issue: https://files.catbox.moe/hvcfsa.mp4

**Comment by theishiopian** [comment]
I think I can do the water thing, will be in the next update.
