### ISSUE TITLE
Arclight server will auto restart when player logout and report  the return value of "java.util.HashMap.get(Object)" is null

### ISSUE THREAD

**Issue by sunnyhome0** [theishiopian/Parrying#42]
https://pastebin.com/FVBrbSz5

It report java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because the return value of "java.util.HashMap.get(Object)" is null

server version:1.18.2
mod version:2.5.2
forge version:40.1.31

**Comment by theishiopian** [comment]
I'll see what I can do, but I make no promises, as I am not familiar with arclight

**Comment by theishiopian** [comment]
I am going to assume this was fixed, if not please reopen
