### ISSUE TITLE
Crash with loot generation(?) in 1.18.2

### ISSUE THREAD

**Issue by sentwayfarer** [theishiopian/Parrying#46]
[crash-2022-08-02_05.55.33-server.txt](https://github.com/theishiopian/Parrying/files/9241579/crash-2022-08-02_05.55.33-server.txt)
I don't know exactly what caused this.

**Comment by theishiopian** [comment]
What is flytre lib? Can you remove it and see if the problem goes away? It's the only thing in the stack trace I don't recognize, and since this is the first time this issue was reported, I can safely assume that the problem is an incompatibility with this mod.

**Comment by theishiopian** [comment]
After some research, it seems flytre lib is a library coremod used for flytre's mods. due to it's closed source nature, finding the problem is likely impossible for now. I'm afraid they are incompatible. If you can prove that the crash occurs without flytrelib I will reopen this.
