### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "net.minecraft.entity.LivingEntity.func_184614_ca()" because "attacker" is null

### ISSUE THREAD

**Issue by SenZ01** [theishiopian/Parrying#47]
Was just running around while getting shot by dozens of Pillagers and then at some point the server just Stopped-

https://pastes.dev/GFmJHMl8Vp

Parry This! version: 2.2.2
Forge: 36.2.33
Minecraft: 1.16
Server: Mohist 1.16.5-1073

heavily edited version of the Mineshafts & Monsters Modpack.

**Comment by theishiopian** [comment]
1.16.5 is no longer supported
