### ISSUE TITLE
[Suggestion] Add config options to allow swords to deflect projectiles by default and configs to be able to choose new projectiles to be parryable

### ISSUE THREAD

**Issue by ghost** [theishiopian/Parrying#48]
I think being able to parry other projectiles would be a fun customization. That's it.

**Comment by ghost** [comment]
Also potentially allow config to turn on projectile deflection for other weapons

**Comment by theishiopian** [comment]
I wont say no, but its not currently being considered.

**Comment by theishiopian** [comment]
After thinking about, I will not be adding deflection without the enchant as an option. I'm not opposed to adding more projectiles to the list though, maybe in a future update.
