### ISSUE TITLE
No keybind for scabbard

### ISSUE THREAD

**Issue by Derpford** [theishiopian/Parrying#54]
#35 mentions this, and a comment on the issue says that it was fixed, but there still appears to be no keybind in the keybinds menu for the scabbard in version `2.5.3`. I'd like to be able to reload my guns without drawing my sword, please :P

**Comment by theishiopian** [comment]
its fixed in dev, i just havent gotten around to finishing the alchemy update. work sucks sometimes

**Comment by Derpford** [comment]
Understandable. Hope it stops sucking so much soon.
