### ISSUE TITLE
[Suggestion] Add more customization via the configs

### ISSUE THREAD

**Issue by ghost** [theishiopian/Parrying#55]
I think the mod could do with an overhaul to it's configuration settings. As the current configs are too boring. Here are a list of potential configs and changes that could be good;

- Allow the player to change the key bind to Dodging and Swift Strike
- A config to enable projectile parrying without the need for the deflection enchantment
- Customizable Weapon Range
- Customizable Invulnerability Reduction
- Customizable Armor and Shield Penetration
- Allow the changing of the sound made when you successfully perform a backstab
- Configure the capacity of the quiver
- Headshot damage for ranged weapons maybe?

**Comment by theishiopian** [comment]
number one is already in in dev. the rest I am against for various reasons.
