### ISSUE TITLE
Weapon Disablement

### ISSUE THREAD

**Issue by nexus140** [theishiopian/Parrying#6]
I would love if this mod had a disable feature for weapons in the config, it would make the mod more highly configurable.
For example, disabling the hammer weapons so that it does not overlap with another weapon based mod that has a hammer type weapon.

**Comment by theishiopian** [comment]
As of aa6a1fb65c32ace8d2293e65be9b512f2f4c4be1 crafting recipes can now be disabled via config. The items will still be available in creative mode. This is the best I can do.
