### ISSUE TITLE
[suggestions] ore dictionary and reach

### ISSUE THREAD

**Issue by k1r0s** [theishiopian/Parrying#7]
hey, congrats for the hard work!

would be nice to detect materials added to the ore dictionary and register weapon variants for each one.

also spears would be a great addition too in order to add poke related strategies with reach.

**Comment by theishiopian** [comment]
Im afraid that your first suggestion isnt feasible, for a couple reasons

1. I would need to generate textures for each weapon, which isnt really practical
2. ore dictionary isnt a thing anymore
3. how do i determine what damage values to give to each?

But as for your second idea, I think you'll like the next update ;)

**Comment by k1r0s** [comment]
lol, I do. Thx
